/* do not edit : generated by ilib_ */
#include "nsp/machine.h"
#include "nsp/interf.h"


extern function int_dsegment;
extern function int_dellipse;
extern function int_dellipsoid;
extern function int_trisurfupd;

static OpWrapTab libdistmesh_func[] = {
  {"dsegment", int_dsegment,NULL},
  {"dellipse", int_dellipse,NULL},
  {"dellipsoid", int_dellipsoid,NULL},
  {"trisurfupd", int_trisurfupd,NULL},
  {(char *) 0, NULL, NULL},
};
int libdistmesh_Interf (int i, Stack stack, int rhs, int opt, int lhs)
{
  if ( libdistmesh_func[i].wrapper == NULL)
     return (*(libdistmesh_func[i].fonc)) (stack, rhs, opt, lhs);
  else 
     return (*(libdistmesh_func[i].wrapper)) (stack, rhs, opt, lhs,libdistmesh_func[i].fonc);
}
void libdistmesh_Interf_Info (int i, char **fname, function (**f))
{
 *fname = libdistmesh_func[i].name;
 *f = libdistmesh_func[i].fonc;
}
